// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdbjbpysyowgovxfgjkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkYmpicHlzeW93Z292eGZnamt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MjY5MTUsImV4cCI6MjA2MjIwMjkxNX0.3QqsYWvvcM5myP2VUQmA_vT6Yxdem3xN_hCtVOWM2rE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);